#!/usr/bin/env python3
"""
Validate or update a deterministic fingerprint lock for substrate proto files.

The lock file ensures protocol-shape changes are explicit and reviewed.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PROTO_DIR = ROOT / "substrate" / "proto" / "v1"
LOCK_FILE = ROOT / "architecture" / "upstream-map" / "proto-lock.sha256"


def compute_lock_content() -> str:
    proto_files = sorted(PROTO_DIR.glob("*.proto"))
    if not proto_files:
        raise RuntimeError(f"No proto files found in {PROTO_DIR}")

    lines = []
    aggregate = hashlib.sha256()
    for proto in proto_files:
        rel = proto.relative_to(ROOT).as_posix()
        digest = hashlib.sha256(proto.read_bytes()).hexdigest()
        line = f"{digest}  {rel}"
        lines.append(line)
        aggregate.update((line + "\n").encode("utf-8"))

    header = [
        "# Auto-generated by tools/upstream_map/check_proto_lock.py --update",
        "# Do not edit manually.",
        f"root-sha256 {aggregate.hexdigest()}",
    ]
    return "\n".join(header + lines) + "\n"


def print_diff(expected: str, actual: str) -> None:
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(LOCK_FILE.relative_to(ROOT)),
        tofile="expected",
        lineterm="",
    )
    for i, line in enumerate(diff):
        if i >= 200:
            print("... diff truncated ...")
            break
        print(line)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite lock file from current proto files",
    )
    args = parser.parse_args()

    expected = compute_lock_content()

    if args.update:
        LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
        LOCK_FILE.write_text(expected, encoding="utf-8")
        print(f"Updated {LOCK_FILE.relative_to(ROOT)}")
        return 0

    if not LOCK_FILE.exists():
        print(f"Missing lock file: {LOCK_FILE.relative_to(ROOT)}")
        print("Run: python3 tools/upstream_map/check_proto_lock.py --update")
        return 1

    actual = LOCK_FILE.read_text(encoding="utf-8")
    if actual != expected:
        print("Proto lock drift detected.")
        print("Run: python3 tools/upstream_map/check_proto_lock.py --update")
        print_diff(expected, actual)
        return 1

    print("Proto lock check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
